import { PRODUCTION_TECHNICIAN, normalizeRole } from './roles';

export const ROLE_NAV_ITEMS = {
  requester: [
    { path: '/requests', label: 'My Requests', icon: 'requests', desc: 'Track your print requests' },
    { path: '/requests/new', label: 'New Request', icon: 'new', desc: 'Submit a new print request' },
  ],
  [PRODUCTION_TECHNICIAN]: [
    { type: 'section', label: 'Dashboards' },
    { path: '/dashboard', label: 'Operational Dashboard', icon: 'dashboard', desc: 'Daily workflow monitoring' },
    { path: '/dashboard/performance', label: 'Performance Dashboard', icon: 'performance', desc: 'Lead time and productivity KPIs' },
    { path: '/dashboard/costs', label: 'Cost Dashboard', icon: 'reports', desc: 'Financial cost analysis' },
    { path: '/dashboard/resources', label: 'Resource Dashboard', icon: 'resource', desc: 'Resource capacity overview' },
    { path: '/dashboard/executive', label: 'Executive Dashboard', icon: 'management', desc: 'Strategic business overview and forecasting' },
    { type: 'section', label: 'Workflow' },
    { path: '/requests', routeName: 'requests.list', label: 'All Requests', icon: 'requests', desc: 'Review and manage requests' },
    { path: '/requests/new', routeName: 'requests.new', label: 'New Request', icon: 'new', desc: 'Create a request' },
    {
      path: '/planning',
      routeName: 'planning.board',
      label: 'Planning',
      icon: 'planning',
      desc: 'Board and schedules',
      children: ['Board', 'Printer Schedule', 'Technician Schedule'],
    },
    { type: 'section', label: 'Reports' },
    { path: '/reports/requests', label: 'Export Requests', icon: 'reports', desc: 'Request exports' },
    { path: '/reports/workload', label: 'Export Workload', icon: 'reports', desc: 'Technician and printer workload exports' },
    { path: '/reports/materials', label: 'Export Materials', icon: 'reports', desc: 'Material consumption exports' },
    { path: '/reports/inventory', label: 'Export Inventory', icon: 'reports', desc: 'Inventory ledger and forecast exports' },
    { path: '/reports/executive', label: 'Export Executive', icon: 'reports', desc: 'Executive report and forecast exports' },
    { path: '/reports/kpis', label: 'Export KPIs', icon: 'reports', desc: 'KPI history exports' },
    { path: '/reports/cost', label: 'Export Cost', icon: 'reports', desc: 'Financial cost exports' },
    { path: '/reports/archive', label: 'Export Archive', icon: 'archive', desc: 'Historical archive exports' },
    { type: 'section', label: 'Archive' },
    { path: '/archive', label: 'Application Archive', icon: 'archive', desc: 'Historical requests' },
    { type: 'section', label: 'Maintenance' },
    { path: '/maintenance', routeName: 'maintenance.printers', label: 'Printer Maintenance', icon: 'resource', desc: 'Preventive printer maintenance' },
    { path: '/maintenance/history', routeName: 'maintenance.history', label: 'Maintenance History', icon: 'reports', desc: 'Maintenance event history' },
    { type: 'section', label: 'Administration' },
    { path: '/stock', label: 'Material Stock', icon: 'resource', desc: 'Stock levels and risk' },
    { path: '/inventory/transactions', label: 'Inventory Transactions', icon: 'reports', desc: 'Stock movement ledger' },
    { path: '/archive/monday-import', label: 'Monday.com Import', icon: 'admin', desc: 'Import historical Monday.com records' },
  ],
  manager: [
    { type: 'section', label: 'Dashboards' },
    { path: '/dashboard', label: 'Operational Dashboard', icon: 'dashboard', desc: 'Operational KPIs' },
    { path: '/dashboard/performance', label: 'Performance Dashboard', icon: 'performance', desc: 'Performance KPIs' },
    { path: '/dashboard/management', label: 'Management Dashboard', icon: 'management', desc: 'Strategic dashboard' },
    { path: '/dashboard/costs', label: 'Cost Dashboard', icon: 'reports', desc: 'Financial cost analysis' },
    { path: '/dashboard/resources', label: 'Resource Dashboard', icon: 'resource', desc: 'Resource capacity overview' },
    { path: '/dashboard/executive', label: 'Executive Dashboard', icon: 'management', desc: 'Strategic business overview and forecasting' },
    { type: 'section', label: 'Workflow' },
    { path: '/requests', routeName: 'requests.list', label: 'All Requests', icon: 'requests', desc: 'Request visibility' },
    {
      path: '/planning',
      routeName: 'planning.board',
      label: 'Planning',
      icon: 'planning',
      desc: 'Board and schedules',
      children: ['Board', 'Printer Schedule', 'Technician Schedule'],
    },
    { type: 'section', label: 'Reports' },
    { path: '/reports/requests', label: 'Export Requests', icon: 'reports', desc: 'Request exports' },
    { path: '/reports/workload', label: 'Export Workload', icon: 'reports', desc: 'Technician and printer workload exports' },
    { path: '/reports/materials', label: 'Export Materials', icon: 'reports', desc: 'Material consumption exports' },
    { path: '/reports/inventory', label: 'Export Inventory', icon: 'reports', desc: 'Inventory ledger and forecast exports' },
    { path: '/reports/executive', label: 'Export Executive', icon: 'reports', desc: 'Executive report and forecast exports' },
    { path: '/reports/kpis', label: 'Export KPIs', icon: 'reports', desc: 'KPI history exports' },
    { path: '/reports/cost', label: 'Export Cost', icon: 'reports', desc: 'Financial cost exports' },
    { path: '/reports/archive', label: 'Export Archive', icon: 'archive', desc: 'Historical archive exports' },
    { type: 'section', label: 'Archive' },
    { path: '/archive', label: 'Application Archive', icon: 'archive', desc: 'Historical requests' },
    { type: 'section', label: 'Maintenance' },
    { path: '/maintenance', routeName: 'maintenance.printers', label: 'Printer Maintenance', icon: 'resource', desc: 'Preventive printer maintenance' },
    { path: '/maintenance/history', routeName: 'maintenance.history', label: 'Maintenance History', icon: 'reports', desc: 'Maintenance event history' },
  ],
  administrator: [
    { type: 'section', label: 'Dashboards' },
    { path: '/dashboard', label: 'Operational Dashboard', icon: 'dashboard', desc: 'Operational KPIs' },
    { path: '/dashboard/performance', label: 'Performance Dashboard', icon: 'performance', desc: 'Performance KPIs' },
    { path: '/dashboard/management', label: 'Management Dashboard', icon: 'management', desc: 'Strategic dashboard' },
    { path: '/dashboard/costs', label: 'Cost Dashboard', icon: 'reports', desc: 'Financial cost analysis' },
    { path: '/dashboard/resources', label: 'Resource Dashboard', icon: 'resource', desc: 'Resource capacity overview' },
    { path: '/dashboard/executive', label: 'Executive Dashboard', icon: 'management', desc: 'Strategic business overview and forecasting' },
    { type: 'section', label: 'Workflow' },
    { path: '/requests', routeName: 'requests.list', label: 'All Requests', icon: 'requests', desc: 'All print requests' },
    { path: '/requests/new', routeName: 'requests.new', label: 'New Request', icon: 'new', desc: 'Create a request' },
    {
      path: '/planning',
      routeName: 'planning.board',
      label: 'Planning',
      icon: 'planning',
      desc: 'Board and schedules',
      children: ['Board', 'Printer Schedule', 'Technician Schedule'],
    },
    { type: 'section', label: 'Reports' },
    { path: '/reports/requests', label: 'Export Requests', icon: 'reports', desc: 'Request exports' },
    { path: '/reports/workload', label: 'Export Workload', icon: 'reports', desc: 'Technician and printer workload exports' },
    { path: '/reports/materials', label: 'Export Materials', icon: 'reports', desc: 'Material consumption exports' },
    { path: '/reports/inventory', label: 'Export Inventory', icon: 'reports', desc: 'Inventory ledger and forecast exports' },
    { path: '/reports/executive', label: 'Export Executive', icon: 'reports', desc: 'Executive report and forecast exports' },
    { path: '/reports/kpis', label: 'Export KPIs', icon: 'reports', desc: 'KPI history exports' },
    { path: '/reports/cost', label: 'Export Cost', icon: 'reports', desc: 'Financial cost exports' },
    { path: '/reports/archive', label: 'Export Archive', icon: 'archive', desc: 'Historical archive exports' },
    { type: 'section', label: 'Archive' },
    { path: '/archive', label: 'Application Archive', icon: 'archive', desc: 'Historical requests' },
    { type: 'section', label: 'Maintenance' },
    { path: '/maintenance', routeName: 'maintenance.printers', label: 'Printer Maintenance', icon: 'resource', desc: 'Preventive printer maintenance' },
    { path: '/maintenance/history', routeName: 'maintenance.history', label: 'Maintenance History', icon: 'reports', desc: 'Maintenance event history' },
    { type: 'section', label: 'Administration' },
    { path: '/stock', label: 'Material Stock', icon: 'resource', desc: 'Stock levels and risk' },
    { path: '/inventory/transactions', label: 'Inventory Transactions', icon: 'reports', desc: 'Stock movement ledger' },
    { path: '/archive/monday-import', label: 'Monday.com Import', icon: 'admin', desc: 'Import historical Monday.com records' },
    {
      path: '/admin',
      label: 'Administration',
      icon: 'admin',
      desc: 'System administration',
      children: ['Users', 'Printers', 'Materials', 'Sites', 'Monday.com Import'],
    },
  ],
};

export const UTILITY_NAV_ITEMS = [
  { path: '/onboarding', label: 'Getting Started', icon: 'help', desc: 'Role guide and workflow help' },
  { path: '/notifications', label: 'Notifications', icon: 'bell', desc: 'System notifications' },
  { path: null, label: 'Profile', icon: 'profile', desc: 'Current user and department' },
];

export const getRoleNavItems = (role) => ROLE_NAV_ITEMS[normalizeRole(role)] || [];

export const getNavigationMapItems = (role) => [
  ...getRoleNavItems(role),
  ...UTILITY_NAV_ITEMS,
];
